// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PolskieBrowary.Data;
using System;

namespace PolskieBrowary.Migrations
{
    [DbContext(typeof(PolskieBrowaryContext))]
    [Migration("20180123150141_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolskieBrowary.Models.Beer", b =>
                {
                    b.Property<int>("BeerID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AlcoholContent");

                    b.Property<string>("BeerGenreID");

                    b.Property<int?>("BeerGenreID1");

                    b.Property<string>("BreveryID");

                    b.Property<int?>("BreveryID1");

                    b.Property<string>("BreveryName");

                    b.Property<decimal>("ExtractContent");

                    b.Property<decimal>("Price");

                    b.HasKey("BeerID");

                    b.HasIndex("BeerGenreID1");

                    b.HasIndex("BreveryID1");

                    b.ToTable("Beer");
                });

            modelBuilder.Entity("PolskieBrowary.Models.BeerGenre", b =>
                {
                    b.Property<int>("BeerGenreID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenreDescription");

                    b.Property<string>("GenreName");

                    b.HasKey("BeerGenreID");

                    b.ToTable("BeerGenre");
                });

            modelBuilder.Entity("PolskieBrowary.Models.Brevery", b =>
                {
                    b.Property<int>("BreveryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BreveryName");

                    b.Property<string>("City");

                    b.Property<string>("Description");

                    b.Property<int>("Established");

                    b.Property<int>("ProductionCapacity");

                    b.HasKey("BreveryID");

                    b.ToTable("Brevery");
                });

            modelBuilder.Entity("PolskieBrowary.Models.Beer", b =>
                {
                    b.HasOne("PolskieBrowary.Models.BeerGenre", "BeerGenre")
                        .WithMany()
                        .HasForeignKey("BeerGenreID1");

                    b.HasOne("PolskieBrowary.Models.Brevery", "Brevery")
                        .WithMany()
                        .HasForeignKey("BreveryID1");
                });
#pragma warning restore 612, 618
        }
    }
}
