// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PolskieBrowary.Data;
using System;

namespace PolskieBrowary.Migrations
{
    [DbContext(typeof(PolskieBrowaryContext))]
    partial class PolskieBrowaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolskieBrowary.Models.Beer", b =>
                {
                    b.Property<int>("BeerID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AlcoholContent");

                    b.Property<int>("BeerGenreID");

                    b.Property<int>("BreveryID");

                    b.Property<string>("BreveryName")
                        .IsRequired();

                    b.Property<decimal>("ExtractContent");

                    b.Property<decimal>("Price");

                    b.HasKey("BeerID");

                    b.HasIndex("BeerGenreID");

                    b.HasIndex("BreveryID");

                    b.ToTable("Beer");
                });

            modelBuilder.Entity("PolskieBrowary.Models.BeerGenre", b =>
                {
                    b.Property<int>("BeerGenreID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenreDescription")
                        .HasMaxLength(1500);

                    b.Property<string>("GenreName")
                        .HasMaxLength(50);

                    b.HasKey("BeerGenreID");

                    b.ToTable("BeerGenre");
                });

            modelBuilder.Entity("PolskieBrowary.Models.Brevery", b =>
                {
                    b.Property<int>("BreveryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BreveryName")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<int>("Established");

                    b.Property<int>("ProductionCapacity");

                    b.HasKey("BreveryID");

                    b.ToTable("Brevery");
                });

            modelBuilder.Entity("PolskieBrowary.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CommentData");

                    b.Property<string>("Comment_text")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("CommentedBeerId");

                    b.Property<string>("UserName");

                    b.HasKey("CommentID");

                    b.HasIndex("CommentedBeerId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("PolskieBrowary.Models.Beer", b =>
                {
                    b.HasOne("PolskieBrowary.Models.BeerGenre", "BeerGenre")
                        .WithMany()
                        .HasForeignKey("BeerGenreID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PolskieBrowary.Models.Brevery", "Brevery")
                        .WithMany()
                        .HasForeignKey("BreveryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PolskieBrowary.Models.Comment", b =>
                {
                    b.HasOne("PolskieBrowary.Models.Beer", "CommentedBeer")
                        .WithMany()
                        .HasForeignKey("CommentedBeerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
